### ISSUE TITLE
Config driven way to ignore certain discord roles

### ISSUE THREAD

**Issue by Jarvvski** [7Cav/IMOBot#9]
I.e. the bot would manage all roles unless told otherwise.

If Smith.J had 4 discord roles, the bot would remove them all and then assign what it should have during the sync. This way roles are kept 'clean'

However, some roles should not be managed by the bot. E.g. S6 Admin/gen staff (same as Teamspeak)

So when you remove all the roles from someone before syncing, you don't remove any of the 'whitelisted' roles

**Comment by VexA3** [comment]
Complete
